name: frontend
description: The frontend for The First Institute application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  provider: ^6.1.2

  # For WebSocket communication with the signaling server
  socket_io_client: ^2.0.3

  # For WebRTC functionality (video, audio)
  flutter_webrtc: ^0.9.48

  # For simple key-value storage
  shared_preferences: ^2.2.3

  # For decoding JWTs to extract payload
  jwt_decoder: ^2.0.1

  # For launching URLs
  url_launcher: ^6.2.6

  # For handling permissions
  permission_handler: ^11.0.1

  # For Firebase services
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.4
  video_player: ^2.8.6
  mediasfu_mediasoup_client: ^1.0.8

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/
